ARG UBUNTU_RELEASE=26.04
ARG BASE_IMAGE=scratch-alias

FROM ubuntu:$UBUNTU_RELEASE AS builder

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        ca-certificates \
        build-essential pkgconf libssl-dev \
        rust-1.93-all rust-1.93-clippy rust-1.93-miri cargo rustc rust-clippy \ 
        vim git \
        hyperfine ripgrep cargo-auditable \
        bash fish \
        autopkgtest dh-make dh-cargo git-buildpackage sbuild ubuntu-dev-tools devscripts \
    && cargo install cargo-vendor-filterer \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*


FROM ${BASE_IMAGE}
COPY --from=builder / /

USER root

EXPOSE 8000 8080

ENTRYPOINT [ "/usr/bin/fish" ]
